// -*- coding: utf-8 -*-
//
// File automatically generated by fgrcc.
  
#include <memory>
#include <utility>

#include <simgear/io/iostreams/CharArrayStream.hxx>
#include <simgear/io/iostreams/zlibstream.hxx>
#include <simgear/embedded_resources/EmbeddedResource.hxx>
#include <simgear/embedded_resources/EmbeddedResourceManager.hxx>

using std::unique_ptr;
using simgear::AbstractEmbeddedResource;
using simgear::RawEmbeddedResource;
using simgear::ZlibEmbeddedResource;
using simgear::EmbeddedResourceManager;

void initFlightGearEmbeddedResources()
{
  EmbeddedResourceManager::instance();
}
