// -*- coding: utf-8 -*-
//
// Header file automatically generated by fgrcc.
   
#ifndef _FG_FLIGHTGEAR_EMBEDDED_RESOURCES
#define _FG_FLIGHTGEAR_EMBEDDED_RESOURCES

void initFlightGearEmbeddedResources();

#endif  // of _FG_FLIGHTGEAR_EMBEDDED_RESOURCES
